= portal-vault-sample

== Status

image:https://github.com/cuioss/portal-vault-sample/actions/workflows/maven.yml/badge.svg[Java CI with Maven,link=https://github.com/cuioss/portal-vault-sample/actions/workflows/maven.yml]
image:http://img.shields.io/:license-apache-blue.svg[License,link=http://www.apache.org/licenses/LICENSE-2.0.html]
image:https://maven-badges.herokuapp.com/maven-central/de.cuioss.portal.vault/portal-vault-sample/badge.svg[Maven Central,link=https://maven-badges.herokuapp.com/maven-central/de.cuioss.portal.vault/portal-vault-sample]

https://sonarcloud.io/summary/new_code?id=cuioss_portal-vault-sample[image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_portal-vault-sample&metric=alert_status[Quality
Gate Status]]
image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_portal-vault-sample&metric=ncloc[Lines of Code,link=https://sonarcloud.io/summary/new_code?id=cuioss_portal-vault-sample]
image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_portal-vault-sample&metric=coverage[Coverage,link=https://sonarcloud.io/summary/new_code?id=cuioss_portal-vault-sample]


https://cuioss.github.io/portal-vault-sample/about.html[Generated Documentation on github-pages]

== What is it?

Portal-based UI-Client for hashicorps vault

=== Maven Coordinates

[source,xml]
----
    <dependency>
        <groupId>de.cuioss.portal.vault</groupId>
        <artifactId>portal-vault-sample</artifactId>
    </dependency>
----


* `SONAR_TOKEN` -> Sonar-Cloud

They are picked up in the predefined pipeline-configurations:

* `.github/workflows/maven.yml`
* `.github/workflows/maven-release.yml`

Ensure that the actions are authorized correctly: Settings > Actions > General > Workflow permissions >  "Read and write permissions" must be selected *not* "Read repository contents permission"

Documentation on how to create a signing key can be found https://github.com/cuioss/cui-parent-pom/blob/master/doc/signing_key.adoc[Documentation at cui-parent-pom] 

A sonar token can be derived from https://sonarcloud.io/account/security

=== Further Steps

* `pom.xml`: Adjust `name` and `description` elements
* `src/site/asciidoc/about.adoc`: Adjust content
* Review / Enable the elements under 'Security' Tab
* Review / Add Collaborators
* Add (link) the resulting maven-documentation: https://github.com/cuioss/cuioss.github.io/edit/main/README.md[github.io-documentation] 
